title: Bharath Motors
logo: https://github.com/mohamednayif/bharathmotors/blob/master/Logo.PNG
description: Authorized Dealer for Sales,Spare and Service of Yamaha and Suzuki Two Wheelers.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
